steps:
  # Step 1: Generate auth token
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Token'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting token generation..."
        gcloud auth print-access-token > /workspace/gcp_token.txt
        if [ $? -eq 0 ]; then
          echo "Token generated successfully."
        else
          echo "Failed to generate token." >&2
          exit 1
        fi

  # Step 2: Build the image locally
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚧 Building Docker image from source code..."
        docker build -t ${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG} .
        if [ $? -ne 0 ]; then
          echo "❌ Docker build failed."
          exit 1
        fi
        echo "✅ Docker image built successfully: ${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}"

  # Step 3: Image scan for vulnerabilities
  - id: 'Image-Analysis'
    name: '${_SCANNER_IMAGE}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting image scan with scanner: ${_SCANNER_IMAGE}"

        exit_code=0

        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /workspace:/workspace \
          -e GCP_PROJECT_ID="${_PROJECT_ID}" \
          -e ORGANIZATION_ID="${_ORGANIZATION_ID}" \
          -e IMAGE_NAME="${_IMAGE_NAME_TO_SCAN}" \
          -e IMAGE_TAG="${_IMAGE_TAG}" \
          -e CONNECTOR_ID="${_CONNECTOR_ID}" \
          -e TRIGGER_ID="${_TRIGGER_ID}" \
          -e IGNORE_ERRORS="${_IGNORE_ERRORS}" \
          -e GCP_ACCESS_TOKEN="$(cat /workspace/gcp_token.txt)" \
          "${_SCANNER_IMAGE}" || exit_code=$?

        echo "Docker run finished with exit code: $exit_code"

        if [ $exit_code -eq 0 ]; then
          echo "✅ Evaluation succeeded: Conformant image."
        elif [ $exit_code -eq 1 ]; then
          echo "❌ Scan failed: Non-conformant image."
          exit 1
        else
          if [ "${_IGNORE_ERRORS}" = "true" ]; then
            echo "⚠️ Server/internal error ignored. Continuing."
          else
            echo "❌ Server/internal error. Exiting."
            exit 1
          fi
        fi

  # Step 4: Configure Docker authentication for Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Configure Docker Auth'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔐 Configuring Docker authentication for Artifact Registry..."
        gcloud auth configure-docker us-east1-docker.pkg.dev -q
        echo "✅ Docker authentication configured."

  # Step 5: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image to Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # _LOCAL_IMAGE="${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}"
        # _FULL_AR_TAG="us-east1-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}"

        # echo "Tagging local image $_LOCAL_IMAGE as $_FULL_AR_TAG"
        docker tag "${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}" "us-east1-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}"
        
        echo "🚀 Pushing $_FULL_AR_TAG..."
        docker push "us-east1-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPOSITORY}/${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}"
        
        echo "✅ Image pushed successfully."

substitutions:
  _IMAGE_NAME_TO_SCAN: 'alpine'
  _ORGANIZATION_ID: '714470867684'
  _CONNECTOR_ID: 'cloudbuild-demo'
  _SCANNER_IMAGE: 'gcr.io/ci-plugin/cloud-build-integration:latest'
  _IMAGE_TAG: 'latest'
  _IMAGE_DIGEST: 'sha256:b0c6491f5ba0dff4c919008f5ab48db97315676136c21796e41fb6326e88d02a'
  _TRIGGER_ID: 'cloud-build-job'
  _PROJECT_ID: 'hcp-tf-test-bhargavi'
  _AR_REPOSITORY: 'vulnerability-scanning'
  _IGNORE_ERRORS: "false"

serviceAccount: "projects/hcp-tf-test-bhargavi/serviceAccounts/461255015551-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
